// /politica — hidden transparency panel. Plan: .plans/politica-transparencia/plan.md.
//
// This is a HIDDEN route: reachable by direct URL only, no Navbar link, no
// `nav.politica` key (omitting the link IS the whole implementation). The page is
// static — the single source of truth is frontend/public/politica/data.json, which
// is generated by scripts/politica/build_data.mjs and verified by four gates. There
// is no backend call and no live API.
//
// The Dashboard.css import is mandatory: the reused primitives (.stat-grid,
// .bar-row, .bar-fill) live in the Dashboard's LAZY chunk, so they are absent from
// main.*.css and would render unstyled here without it.

import React, { useEffect, useState, useMemo } from 'react';
import { useI18n } from '../../i18n';
import '../Dashboard.css';
import './Politica.css';

import PoliticaKpis from './PoliticaKpis';
import PoliticaSeries from './PoliticaSeries';
import PoliticaDossier from './PoliticaDossier';
import PoliticaSources from './PoliticaSources';

const DATA_URL = `${process.env.PUBLIC_URL || ''}/politica/data.json`;

// Section registry drives BOTH the anchor nav and the render order, so the two can
// never drift apart.
const SECTIONS = [
  { id: 'kpis', key: 'navKpis', Comp: PoliticaKpis },
  { id: 'dossier', key: 'navDossier', Comp: PoliticaDossier },
  { id: 'series', key: 'navSeries', Comp: PoliticaSeries },
];

export const PoliticaContext = React.createContext(null);

export function usePolitica() {
  const ctx = React.useContext(PoliticaContext);
  if (!ctx) throw new Error('usePolitica must be used inside Politica');
  return ctx;
}

function PoliticaHeader() {
  const { t } = useI18n();
  return (
    <header className="politica-header">
      <p className="politica-kicker">{t('politica.kicker')}</p>
      <h1 className="politica-title">{t('politica.title')}</h1>
      <p className="politica-intro">{t('politica.intro')}</p>
    </header>
  );
}

function SectionNav() {
  const { t } = useI18n();
  return (
    <nav className="politica-nav" aria-label={t('politica.kicker')}>
      {SECTIONS.map((s) => (
        <a key={s.id} className="politica-nav__chip" href={`#politica-${s.id}`}>
          {t(`politica.${s.key}`)}
        </a>
      ))}
      <a className="politica-nav__chip" href="#politica-scope">
        {t('politica.navSources')}
      </a>
    </nav>
  );
}

// Exported so Gate 4 (scripts/politica/verify_render.mjs) can render the whole
// page — provider + every section — and catch shell-level wiring bugs that a
// per-section render would miss.
export function PoliticaBody({ data }) {
  const { lang, t } = useI18n();
  // `data` arrives as a prop: this component OWNS the provider, so it cannot
  // consume it (the sections below are the consumers).
  const ctx = useMemo(() => ({ data, lang }), [data, lang]);

  return (
    <PoliticaContext.Provider value={ctx}>
      <SectionNav />
      {SECTIONS.map(({ id, Comp }) => (
        <section key={id} id={`politica-${id}`} className="politica-section">
          <Comp />
        </section>
      ))}
      <section id="politica-scope" className="politica-section">
        <PoliticaSources />
      </section>
      <p style={{ textAlign: 'center', marginTop: 32 }}>
        <a className="politica-source" href="#top">
          ↑ {t('politica.backTop')}
        </a>
      </p>
    </PoliticaContext.Provider>
  );
}

export default function Politica() {
  const { t } = useI18n();
  const [state, setState] = useState({ status: 'loading', data: null, error: null });

  useEffect(() => {
    // A hidden, dated page: the data never changes at runtime, so there is no
    // re-fetch and no polling — a single load on mount is the whole story.
    let cancelled = false;
    fetch(DATA_URL)
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((json) => {
        if (!cancelled) setState({ status: 'ready', data: json, error: null });
      })
      .catch((err) => {
        if (!cancelled) setState({ status: 'error', data: null, error: err.message });
      });
    return () => { cancelled = true; };
  }, []);

  // The page is hidden and holds political-legal content: keep it out of search
  // indexes for as long as it is mounted.
  useEffect(() => {
    const meta = document.createElement('meta');
    meta.name = 'robots';
    meta.content = 'noindex';
    document.head.appendChild(meta);
    return () => { document.head.removeChild(meta); };
  }, []);

  if (state.status === 'loading') {
    return (
      <div className="politica-page">
        <div className="politica-loading" role="status">{t('politica.loading')}</div>
      </div>
    );
  }

  if (state.status === 'error') {
    return (
      <div className="politica-page">
        <div className="politica-error" role="alert">
          <strong>{t('politica.loadError')}</strong>
          <p style={{ margin: '6px 0 0' }}>
            {t('politica.dataPath')}: <code>{DATA_URL}</code>
          </p>
          <p style={{ margin: '6px 0 0' }}>{state.error}</p>
          <button
            type="button"
            className="politica-nav__chip"
            style={{ marginTop: 10 }}
            onClick={() => window.location.reload()}
          >
            {t('politica.retry')}
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="politica-page" id="top">
      <PoliticaHeader />
      <PoliticaBody data={state.data} />
    </div>
  );
}
