stages:
  - setup
  - deploy

variables:
  DOCKER_DRIVER: overlay2

# Job para configurar o ambiente com Docker Compose
setup_environment:
  stage: setup
  image: docker:24.0
  services:
    - docker:24.0-dind
  script:
    - apk add --no-cache py3-pip
    - pip install docker-compose
    - docker-compose -f docker-compose.yml up -d
  only:
    - main

# Job para fazer o deploy
deploy_application:
  stage: deploy
  image: docker:24.0
  services:
    - docker:24.0-dind
  script:
    - docker-compose -f docker-compose.yml up -d
  only:
    - main
