stages:
  - setup
  - deploy

variables:
  DOCKER_DRIVER: overlay2

# Job para configurar o ambiente com Docker Compose
setup_environment:
  stage: setup
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  before_script:
    # Adiciona dependências necessárias para instalar docker-compose
    - apk add --no-cache py3-pip libffi-dev py3-cryptography py3-setuptools
    # Instala docker-compose usando pip
    - pip install --no-cache-dir docker-compose
  script:
    - docker-compose -f docker-compose.yml up -d
  only:
    - main

# Job para fazer o deploy
deploy_application:
  stage: deploy
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  before_script:
    # Adiciona dependências necessárias para instalar docker-compose
    - apk add --no-cache py3-pip libffi-dev py3-cryptography py3-setuptools
    # Instala docker-compose usando pip
    - pip install --no-cache-dir docker-compose
  script:
    - docker-compose -f docker-compose.yml up -d
  only:
    - main
