stages:
  - setup
  - deploy

variables:
  DOCKER_DRIVER: overlay2

# Job para configurar o ambiente com Docker Compose
setup_environment:
  stage: setup
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  before_script:
    # Baixar e instalar o docker-compose diretamente como binário
    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
  script:
    - docker-compose -f docker-compose.yml up -d
  only:
    - main

# Job para fazer o deploy
deploy_application:
  stage: deploy
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  before_script:
    # Baixar e instalar o docker-compose diretamente como binário
    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
  script:
    - docker-compose -f docker-compose.yml up -d
  only:
    - main
