[mongo]
service = "mongo"
image = "mongo:latest"
container_name = "mongo"
environment = [
  "MONGO_INITDB_ROOT_USERNAME=root",
  "MONGO_INITDB_ROOT_PASSWORD=example"
]
ports = [
  "27017:27017"
]
volumes = [
  "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro",
  "./mongo_data:/data/db"
]
resources_limits_cpus = "1.0"

[frontend]
service = "frontend"
builder = "dockerfile"
context = "./frontend"
container_name = "frontend"
ports = [
  "3000:3000"
]
depends_on = [
  "backend"
]
restart_policy_type = "always"
resources_limits_cpus = "1.0"

[backend]
service = "backend"
builder = "dockerfile"
context = "./backend"
container_name = "backend"
environment = [
  "MONGO_URI=mongodb://root:example@mongo:27017/"
]
ports = [
  "5000:5000"
]
volumes = [
  "./backend:/app"
]
depends_on = [
  "mongo"
]
resources_limits_cpus = "1.0"

[network]
driver = "bridge"
name = "app-network"
