# Configuração do MongoDB

# Configuração do Frontend
[frontend]
service = "frontend"
builder = "NIXPACKS"
buildCommand = "cd frontend && npm run install:prod && npm run build"
startCommand = "cd frontend && npm run serve"
ports = [
  "3000:3000"
]
restart_policy_type = "always"
resources_limits_cpus = "1.0"


# Configuração da Rede
[network]
driver = "bridge"
name = "app-network"
