# Configuração do MongoDB

# Configuração do Frontend
[frontend]
service = "frontend"
builder = "NODE"
buildCommand = "chmod +x build-frontend.sh && ./build-frontend.sh"
startCommand = "chmod +x run-frontend.sh && ./run-frontend.sh"
ports = [
  "3000:3000"
]
depends_on = [
  "backend"
]
restart_policy_type = "always"
resources_limits_cpus = "1.0"


# Configuração da Rede
[network]
driver = "bridge"
name = "app-network"
