version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G

  flask-app:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 12G

volumes:
  mongo_data:
