"""Conservation units (Unidades de Conservação ICMBio) point-in-polygon lookup.

Loads conservation_units.json (generated by extract_conservation_units.py) once at
startup and provides O(n) point classification for fire alert detection.
"""
from __future__ import annotations

import json
import logging
import os

from _geo import point_in_polygon

logger = logging.getLogger(__name__)

_DATA_FILE = os.path.join(os.path.dirname(__file__), "conservation_units.json")

_units: list[tuple[str, dict, list]] = []


def load_conservation_units() -> None:
    """Load conservation_units.json into memory."""
    global _units
    if not os.path.exists(_DATA_FILE):
        logger.warning("conservation_units.json not found — UC lookup disabled")
        return
    with open(_DATA_FILE, encoding="utf-8") as f:
        data = json.load(f)
    _units = [
        (name, {k: v for k, v in meta.items() if k != "rings"}, meta["rings"])
        for name, meta in data.items()
    ]
    logger.info("Loaded %d conservation unit polygons", len(_units))


def classify_point(lon: float, lat: float) -> dict | None:
    """Return UC info if (lon, lat) is inside any conservation unit, else None.

    Returns: {"name": str, "category": str, "group": str,
              "state_abbr": str, "state_name": str}
    """
    for name, meta, rings in _units:
        if point_in_polygon(lon, lat, rings):
            return {"name": name, **meta}
    return None
