"""Indigenous lands (Terras Indígenas) point-in-polygon lookup.

Loads indigenous_lands.json (generated by extract_indigenous_lands.py) once at
startup and provides O(n) point classification for fire alert detection.
"""
from __future__ import annotations

import json
import logging
import os

from _geo import point_in_polygon

logger = logging.getLogger(__name__)

_DATA_FILE = os.path.join(os.path.dirname(__file__), "indigenous_lands.json")

# List of (name, meta_dict, rings) loaded at startup
_lands: list[tuple[str, dict, list]] = []


def load_indigenous_lands() -> None:
    """Load indigenous_lands.json into memory."""
    global _lands
    if not os.path.exists(_DATA_FILE):
        logger.warning("indigenous_lands.json not found — TI lookup disabled")
        return
    with open(_DATA_FILE, encoding="utf-8") as f:
        data = json.load(f)
    _lands = [
        (name, {k: v for k, v in meta.items() if k != "rings"}, meta["rings"])
        for name, meta in data.items()
    ]
    logger.info("Loaded %d indigenous land polygons", len(_lands))


def classify_point(lon: float, lat: float) -> dict | None:
    """Return TI info if (lon, lat) is inside any indigenous land, else None.

    Returns: {"name": str, "state_abbr": str, "state_name": str, "municipality": str}
    """
    for name, meta, rings in _lands:
        if point_in_polygon(lon, lat, rings):
            return {"name": name, **meta}
    return None
