name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the Node.js version you need

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Run the build script (build.sh)
      - name: Build project
        run: |
          chmod +x ./build.sh
          ./build.sh

      # Run tests (if applicable)
      - name: Run tests
        run: |
          npm test  # This assumes you have tests in your project

      # Run the server (run.sh)
      - name: Run server
        run: |
          chmod +x ./run.sh
          ./run.sh
