name: Docker Compose CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Set up Docker Compose
    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    # Build and run containers with Docker Compose
    - name: Docker Compose Build and Run
      run: docker-compose up -d --build

    # Verify if services are running
    - name: Verify Services
      run: docker-compose ps
