name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: ./node  # Ajuste este caminho se necess치rio

      # Run the build script (if applicable)
      - name: Build project
        run: npm run build
        working-directory: ./node  # Ajuste este caminho se necess치rio

      # Run tests (if applicable)
      - name: Run tests
        run: npm test
        working-directory: ./node  # Ajuste este caminho se necess치rio

      # Deploy or start the server
      - name: Run server
        run: npm start
        working-directory: ./node  # Ajuste este caminho se necess치rio
